In [48]:
import kagglehub as kgl
import pandas as pd
import chess
import chess.pgn
import chess.engine

In [49]:
remote = kgl.dataset_download("datasnaek/chess")
df = pd.read_csv(f"{remote}/games.csv")
df_moves = df.moves #데이터에서 필요한 것만 추출한다.
df_moves.head()

0    d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...
1    d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...
2    e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...
3    d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...
4    e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...
Name: moves, dtype: str

In [50]:
#for i in range(df_moves.count()):
#    with open(f"./data/game_{i}.txt", "w") as f:
#        f.write(df_moves[i])

In [51]:
path = "./data/game_0.txt"

with open(path, "r", encoding="utf-8") as rec:
    texts = rec.read().split()
    rec.seek(0)
    game = chess.pgn.read_game(rec)

engine = chess.engine.SimpleEngine.popen_uci("./stockfish/stockfish")
anal_df = pd.DataFrame(texts, columns=["move"])

board = game.board()
lst_boards = []

In [52]:
#move를 데이터프레임에 담기, 또 move 별로 나누기
anal_df

    move
0     d4
1     d5
2     c4
3     c6
4   cxd5
5     e6
6   dxe6
7   fxe6
8    Nf3
9   Bb4+
10   Nc3
11   Ba5
12   Bf4

In [53]:
for move in game.mainline_moves():
    board.push(move)
    lst_boards.append(board.copy())
    anal_df["board"] = board.copy()

In [54]:
anal_df

    move                                              board
0     d4  r n b q k . n r\np p . . . . p p\n. . p . p . ...
1     d5  r n b q k . n r\np p . . . . p p\n. . p . p . ...
2     c4  r n b q k . n r\np p . . . . p p\n. . p . p . ...
3     c6  r n b q k . n r\np p . . . . p p\n. . p . p . ...
4   cxd5  r n b q k . n r\np p . . . . p p\n. . p . p . ...
5     e6  r n b q k . n r\np p . . . . p p\n. . p . p . ...
6   dxe6  r n b q k . n r\np p . . . . p p\n. . p . p . ...
7   fxe6  r n b q k . n r\np p . . . . p p\n. . p . p . ...
8    Nf3  r n b q k . n r\np p . . . . p p\n. . p . p . ...
9   Bb4+  r n b q k . n r\np p . . . . p p\n. . p . p . ...
10   Nc3  r n b q k . n r\np p . . . . p p\n. . p . p . ...
11   Ba5  r n b q k . n r\np p . . . . p p\n. . p . p . ...
12   Bf4  r n b q k . n r\np p . . . . p p\n. . p . p . ...

In [55]:
anal = engine.analyse(lst_boards[12], chess.engine.Limit(time=1))
#anal에서 필요한 거: score, pv
anal_df["score"] = anal["score"]
anal_df["pv"] = [anal["pv"]]
anal_df

ValueError: Length of values (1) does not match length of index (13)

In [ ]:
anal

{'string': 'Network replica 1: Shared memory.',
 'depth': 19,
 'seldepth': 34,
 'multipv': 1,
 'score': PovScore(Cp(-441), BLACK),
 'nodes': 884304,
 'nps': 884304,
 'hashfull': 338,
 'tbhits': 0,
 'time': 1.0,
 'pv': [Move.from_uci('g8f6'),
  Move.from_uci('e2e3'),
  Move.from_uci('e8g8'),
  Move.from_uci('d1c2'),
  Move.from_uci('f6d5'),
  Move.from_uci('f4g3'),
  Move.from_uci('b8d7'),
  Move.from_uci('f1d3'),
  Move.from_uci('d7f6'),
  Move.from_uci('e1g1'),
  Move.from_uci('d5b4'),
  Move.from_uci('c2e2'),
  Move.from_uci('b4d3'),
  Move.from_uci('e2d3'),
  Move.from_uci('d8e7'),
  Move.from_uci('f1d1')]}